# Environment-specific values for dev
# These values override the default app values

# Development environment configuration
environment: dev

# Resource allocation for dev (smaller than prod)
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Development-specific environment variables
env:
  - name: ENVIRONMENT
    value: "dev"
  - name: LOG_LEVEL
    value: "debug"
  - name: DEBUG
    value: "true"

# Pod labels for dev environment
podLabels:
  environment: dev
  tier: development

# Annotations for dev
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9113"
  prometheus.io/path: "/metrics"
  dev.observability/enabled: "true"

# Disable autoscaling in dev
autoscaling:
  enabled: false

# Single replica for dev
replicaCount: 1

# Service configuration for dev
service:
  type: ClusterIP
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"