# Default values for observability-test app
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: nginx
  tag: "1.27.3-alpine"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Nginx metrics configuration
metrics:
  enabled: true
  port: 9113
  image:
    repository: nginx/nginx-prometheus-exporter
    tag: "1.3.0"
    pullPolicy: IfNotPresent

# Resource limits and requests
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Health checks
livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

# Pod annotations for observability
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9113"
  prometheus.io/path: "/metrics"

# Pod labels
podLabels:
  app: observability-test
  version: v1.0.0

# Environment variables
env:
  - name: APP_NAME
    value: "observability-test"
  - name: APP_VERSION
    value: "v1.0.0"
  - name: LOG_LEVEL
    value: "info"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 101
  readOnlyRootFilesystem: true

# Network policy
networkPolicy:
  enabled: false

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}