name: terraform

on:
  pull_request:
    branches: [ env/dev, env/staging, env/prod ]
    paths:
      - 'infra/envs/**'
      - 'modules/**'
      - '.github/workflows/terraform.yaml'
  push:
    branches: [ env/dev, env/staging, env/prod ]
    paths:
      - 'infra/envs/**'
      - 'modules/**'
      - '.github/workflows/terraform.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        type: choice
        options:
          - dev
          - staging
          - prod
        required: true
        default: dev
      action:
        description: "Action to perform"
        type: choice
        options:
          - plan
          - apply
        required: true
        default: plan

permissions:
  id-token: write
  contents: read
  issues: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_VERSION: "1.6.6"
  AWS_REGION: ${{ vars.TF_BACKEND_REGION }}

jobs:
  plan:
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.action == 'plan')
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || (github.base_ref == 'env/dev' && 'dev' || github.base_ref == 'env/staging' && 'staging' || github.base_ref == 'env/prod' && 'prod' || '') }}
    defaults:
      run:
        shell: bash
        working-directory: infra/envs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (remote backend)
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_BACKEND_BUCKET }}" \
            -backend-config="key=global/terraform.tfstate" \
            -backend-config="region=${{ vars.TF_BACKEND_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ vars.TF_BACKEND_DDB_TABLE }}" \
            -backend-config="kms_key_id=${{ vars.TF_BACKEND_KMS_KEY_ID }}" \
            -backend-config="acl=private" \
            -backend-config="workspace_key_prefix=envs"

      - name: Terraform Fmt Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Select Workspace
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENV="${{ inputs.environment }}"
          else
            case "${GITHUB_BASE_REF}" in
              env/dev) ENV="dev" ;;
              env/staging) ENV="staging" ;;
              env/prod) ENV="prod" ;;
              *) ENV="dev" ;;
            esac
          fi
          terraform workspace list | grep -q " $ENV$" || terraform workspace new "$ENV"
          terraform workspace select "$ENV"

      - name: Terraform Plan
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENV="${{ inputs.environment }}"
          else
            case "${GITHUB_BASE_REF}" in
              env/dev) ENV="dev" ;;
              env/staging) ENV="staging" ;;
              env/prod) ENV="prod" ;;
              *) ENV="dev" ;;
            esac
          fi
          VARS="${ENV}/terraform.tfvars"
          terraform plan -var-file="$VARS" -var "region=${AWS_REGION}" -var "aws_profile=" -out=tfplan

  apply:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply')
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || (github.ref_name == 'env/dev' && 'dev' || github.ref_name == 'env/staging' && 'staging' || github.ref_name == 'env/prod' && 'prod' || '') }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        shell: bash
        working-directory: infra/envs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (remote backend)
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_BACKEND_BUCKET }}" \
            -backend-config="key=global/terraform.tfstate" \
            -backend-config="region=${{ vars.TF_BACKEND_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ vars.TF_BACKEND_DDB_TABLE }}" \
            -backend-config="kms_key_id=${{ vars.TF_BACKEND_KMS_KEY_ID }}" \
            -backend-config="acl=private" \
            -backend-config="workspace_key_prefix=envs"

      - name: Terraform Fmt Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Select Workspace
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENV="${{ inputs.environment }}"
          else
            case "${GITHUB_REF_NAME}" in
              env/dev) ENV="dev" ;;
              env/staging) ENV="staging" ;;
              env/prod) ENV="prod" ;;
            esac
          fi
          terraform workspace list | grep -q " $ENV$" || terraform workspace new "$ENV"
          terraform workspace select "$ENV"

      - name: Wait for manual approval before production
        if: (github.ref_name == 'env/prod') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod')
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: rnato35
          minimum-approvals: 1
          issue-title: "Manual approval required for production apply"
          issue-body: "Please approve this production deployment."
          exclude-workflow-initiator-as-approver: false

      - name: Terraform Plan
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENV="${{ inputs.environment }}"
          else
            case "${GITHUB_REF_NAME}" in
              env/dev) ENV="dev" ;;
              env/staging) ENV="staging" ;;
              env/prod) ENV="prod" ;;
            esac
          fi
          VARS="${ENV}/terraform.tfvars"
          terraform plan -var-file="$VARS" -var "region=${AWS_REGION}" -var "aws_profile=" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
